[project]
name = "review-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.121.0",
    "google-genai>=1.48.0",
    "ollama>=0.6.0",
    "pydantic>=2.12.3",
    "uvicorn>=0.38.0",
]
